distance_tolerance: 0.1
intensity_lower_threshold: 200
intensity_upper_threshold: 10000
update_rate: 0.25
dock_dist_threshold: 0.15
undock_dist_threshold: 1.0
undock_after_failed_dock: true

stations:
- frame_id: station_charger
  reflector_distance: 0.28
  approach:
    poses: [[-0.76, 0.0, 0], [-0.56, 0.0, 0], [-0.47, 0.0, 0]] # in frame_id coords
    stop_condition:
      topic: '/power_state'
      message_fields: ['charging']
      compare_values: [True]
  departure:
    poses: [[-0.8, 0.0, 0]]
- frame_id: station_travel_box
  reflector_distance: 0.95
  approach:
    poses: [[-2.20, 0.0, 0.0], [-0.6, 0.0, -0.035], [-0.38, 0.0, -0.035], [-0.312, 0.0, -0.035]] # in frame_id coords
  departure:
    poses: [[-0.38, 0.0, -0.035], [-0.6, 0.0, -0.035], [-2.20, 0.0, 0.0]] # in frame_id coords
