%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/melodic/.*$
%global __requires_exclude_from ^/opt/ros/melodic/.*$

Name:           ros-melodic-cob-hardware-config
Version:        0.7.2
Release:        1%{?dist}
Summary:        ROS cob_hardware_config package

License:        Apache 2.0
URL:            http://ros.org/wiki/cob_hardware_config
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-melodic-cob-calibration-data
Requires:       ros-melodic-cob-description
Requires:       ros-melodic-cob-omni-drive-controller
Requires:       ros-melodic-costmap-2d
Requires:       ros-melodic-diagnostic-aggregator
Requires:       ros-melodic-joint-state-controller
Requires:       ros-melodic-joint-state-publisher
Requires:       ros-melodic-joint-trajectory-controller
Requires:       ros-melodic-laser-filters
Requires:       ros-melodic-position-controllers
Requires:       ros-melodic-raw-description
Requires:       ros-melodic-robot-state-publisher
Requires:       ros-melodic-roslaunch
Requires:       ros-melodic-rostest
Requires:       ros-melodic-rviz
Requires:       ros-melodic-velocity-controllers
Requires:       ros-melodic-xacro
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-cob-supported-robots
BuildRequires:  ros-melodic-roslaunch
BuildRequires:  ros-melodic-rostest

%description
This package contains configuration for each robot instance (e.g. cob4-X,
raw3-X). There is a directory for each robot with configuration about urdf and
hardware/device configurations.

%prep
%autosetup

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_LIBDIR="lib" \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/melodic

%changelog
* Sat Nov 09 2019 Felix Messmer <felixmessmer@gmail.com> - 0.7.2-1
- Autogenerated by Bloom

