Name:           ros-kinetic-cob-hardware-config
Version:        0.6.7
Release:        1%{?dist}
Summary:        ROS cob_hardware_config package

Group:          Development/Libraries
License:        LGPL
URL:            http://ros.org/wiki/cob_hardware_config
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-kinetic-cob-calibration-data
Requires:       ros-kinetic-cob-description
Requires:       ros-kinetic-cob-omni-drive-controller
Requires:       ros-kinetic-diagnostic-aggregator
Requires:       ros-kinetic-joint-state-controller
Requires:       ros-kinetic-joint-trajectory-controller
Requires:       ros-kinetic-position-controllers
Requires:       ros-kinetic-raw-description
Requires:       ros-kinetic-roslaunch
Requires:       ros-kinetic-rostest
Requires:       ros-kinetic-schunk-description
Requires:       ros-kinetic-ur-description
Requires:       ros-kinetic-velocity-controllers
Requires:       ros-kinetic-xacro
BuildRequires:  ros-kinetic-catkin
BuildRequires:  ros-kinetic-cob-supported-robots
BuildRequires:  ros-kinetic-roslaunch
BuildRequires:  ros-kinetic-rostest

%description
This package contains configuration for each robot instance (e.g. cob4-X,
raw3-X). There is a directory for each robot with configuration about urdf and
hardware/device configurations.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Sat Aug 05 2017 Nadia Hammoudeh Garcia <nhg@ipa.fhg.de> - 0.6.7-1
- Autogenerated by Bloom

* Sat Aug 05 2017 Nadia Hammoudeh Garcia <nhg@ipa.fhg.de> - 0.6.7-0
- Autogenerated by Bloom

