%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/noetic/.*$
%global __requires_exclude_from ^/opt/ros/noetic/.*$

Name:           ros-noetic-cob-hardware-config
Version:        0.7.5
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS cob_hardware_config package

License:        Apache 2.0
URL:            http://ros.org/wiki/cob_hardware_config
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-noetic-cob-calibration-data
Requires:       ros-noetic-cob-description
Requires:       ros-noetic-cob-omni-drive-controller
Requires:       ros-noetic-costmap-2d
Requires:       ros-noetic-diagnostic-aggregator
Requires:       ros-noetic-joint-state-controller
Requires:       ros-noetic-joint-state-publisher
Requires:       ros-noetic-joint-state-publisher-gui
Requires:       ros-noetic-joint-trajectory-controller
Requires:       ros-noetic-laser-filters
Requires:       ros-noetic-position-controllers
Requires:       ros-noetic-raw-description
Requires:       ros-noetic-robot-state-publisher
Requires:       ros-noetic-rviz
Requires:       ros-noetic-velocity-controllers
Requires:       ros-noetic-xacro
BuildRequires:  ros-noetic-catkin
BuildRequires:  ros-noetic-cob-supported-robots
BuildRequires:  ros-noetic-roslaunch
BuildRequires:  ros-noetic-rostest
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
This package contains configuration for each robot instance (e.g. cob4-X,
raw3-X). There is a directory for each robot with configuration about urdf and
hardware/device configurations.

%prep
%autosetup

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_LIBDIR="lib" \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/noetic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/noetic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/noetic

%changelog
* Wed Dec 02 2020 Felix Messmer <felixmessmer@gmail.com> - 0.7.5-1
- Autogenerated by Bloom

