scan_filter_chain:
- name: range
  type: laser_filters/LaserScanRangeFilter
  params:
    lower_threshold: 0.01
    upper_threshold: 3
- name: intensity
  type: laser_filters/LaserScanIntensityFilter
  params:
    lower_threshold: 250
    upper_threshold: 9000
    disp_histogram: 0
