nodes:
  b_caster_rotation_joint:
    dcf_overlay:
      607C: '9956.0'
  fl_caster_rotation_joint:
    dcf_overlay:
      607C: '131615.5'
  fr_caster_rotation_joint:
    dcf_overlay:
      607C: '-109706.5'
