nodes:
  b_caster_rotation_joint:
    dcf_overlay:
      607C: '12757.0'
  fl_caster_rotation_joint:
    dcf_overlay:
      607C: '129944.49999999999'
  fr_caster_rotation_joint:
    dcf_overlay:
      607C: '-109200.5'
